sudo: false
language: node_js

before_install:
  - gem install sass
  - gem install compass
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
notifications:
  email:
    recipients:
      - tech@chihuo.org
    on_success: [change]
    on_failure: [always]
