sudo: false
language: node_js

before_install:
  - "export DISPLAY::99.0"
  - "sh -e /etc/init.d/xvfb start"
  - gem install sass
  - gem install compass
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
